翻譯 a_reliable_friend.snbt
SiongSng/Roguelike-Adventures-and-Dungeons-2-zh_TW pull request #1
Opened 2023-03-20 07:08 UTC by MAG10d

2023-03-20 10:45 UTC, SiongSng requested changes
非常感謝您的翻譯貢獻
以下我有注意到幾個小問題麻煩您修正
可以直接按下 「Commit suggestion」這個按鈕就會直接按照我的建議修改翻譯檔案了！

2023-03-20 10:45 UTC, SiongSng commented on pack/config/ftbquests/quests/chapters/a_reliable_friend.snbt
> +				"一旦你擁有了一隻 Doggy Talents 的狗，你就可以用手持木棍（主手或副手）右鍵點擊它，打開狗的資訊/技能菜單。"
```suggestion
				"一旦你擁有了一隻 Doggy Talents 的狗，你就可以用手持木棍（主手或副手）右鍵點擊它，打開狗的資訊/技能選單。"
```

menu 應翻譯為選單而非菜單

2023-03-20 10:45 UTC, SiongSng commented on pack/config/ftbquests/quests/chapters/a_reliable_friend.snbt
> +				"這個選單允許你更改狗狗的名字、切換其行為、添加技能，以及切換是否聽從其他玩家的指令。在選單中，你的狗狗的基本等級、凶猛等級和等級點數將顯示在名字框下方。"
```suggestion
				"這個選單允許你更改狗狗的名字、切換其行為、新增技能，以及切換是否聽從其他玩家的指令。在選單中，你的狗狗的基本等級、凶猛等級和等級點數將顯示在名字框下方。"
```

請使用在地化用語，用 `新增` 替代 `添加`

2023-03-20 10:45 UTC, SiongSng commented on pack/config/ftbquests/quests/chapters/a_reliable_friend.snbt
> +				"這會給你的狗狗一個項圈！要裝備項圈，你需要用主手點擊你的狗狗，並將項圈放在主手。你可以像 Wearable Backpacks 模組中一樣自定義項圈的顏色！"
```suggestion
				"這會給你的狗狗一個項圈！要裝備項圈，你需要用主手點擊你的狗狗，並將項圈放在主手。你可以像 Wearable Backpacks 模組中一樣自訂項圈的顏色！"
```

2023-03-20 10:45 UTC, SiongSng commented on pack/config/ftbquests/quests/chapters/a_reliable_friend.snbt
> +			description: ["這根特殊的棒子可以讓你的狗狗在 100 個刻（5 秒）、200 個刻（10 秒）和 100 個刻（5 秒）的時間內分別獲得發光 1 級、速度 6 級和再生 1 級的效果。"]
```suggestion
			description: ["這根特殊的棒子可以讓你的狗狗在 100 個刻（5 秒）、200 個刻（10 秒）和 100 個刻（5 秒）的時間內分別獲得發光 1 級、速度 6 級和回復 1 級的效果。"]
```

此效果是 `回復` 而非 `再生`，詳見 [Minecraft Wiki](https://minecraft.fandom.com/zh/wiki/%E7%94%9F%E5%91%BD%E6%81%A2%E5%A4%8D)

2023-03-20 10:45 UTC, SiongSng commented on pack/config/ftbquests/quests/chapters/a_reliable_friend.snbt
> +				"從而防止狗死亡。狗的生命值一旦恢復到 1 HP 以上，它就會自動退出此模式，但是退出後它的生命值不會恢復到滿值。如果你想讓狗在完全恢復生命值的情況下強制退出此模式，請餵它蛋糕。"
```suggestion
				"從而防止狗死亡。狗的生命值一旦恢復到 1 HP 以上，它就會自動退出此模式，但是退出後它的生命值不會恢復到滿值。如果你想讓狗在完全恢復生命值的情況下強制退出此模式，請餵牠蛋糕。"
```

狗是動物，應使用動物的他（牠）

2023-03-20 23:42 UTC, MAG10d commented
ok

2023-03-22 12:40 UTC, SiongSng approved these changes
LGTM

2023-03-22 12:41 UTC, merged